TrainModelConfig:
  MODEL_PATH : "artifacts/models/runs/detect/train/weights/last.pt"
  DATA_YAML : "data/processed/data.yaml"
  PROJECT_DIR : "artifacts/models"
  RUN_NAME : "train"
  EPOCHS: 10
  IMGSZ: 640
  DEVICE: 'cpu'
  RESUME: True

EvaluateModelConfig:
  MODEL_PATH: "artifacts/models/runs/detect/train/weights/best.pt"
  DATA_YAML: "data/processed/data.yaml"
  PROJECT_DIR: "artifacts/models"
  DEVICE: 'cpu'
  RUN_NAME: "eval"
  NUM_SAMPLES: 5
  TRAIN_DIR: "artifacts/models/runs/detect/train"
  EVAL_REPORT_PATH: "artifacts/models/runs/detect/train/evaluate.md"